---
apiVersion: v1
kind: Service
metadata:
  name: front-end-deployment
  labels:
    app: front-end
  namespace: sock-shop
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
    appProtocol: http
    nodePort: 30001
  selector:
    app: front-end
